CREATE TABLE IF NOT EXISTS public.pre_production_shoots (
    external_lead_id character varying(100) NOT NULL PRIMARY KEY,
    drive_link text,
    num_images integer DEFAULT 0,
    camera_used character varying(255),
    upload_notes text,
    photo_first_clip text,
    photo_last_clip text,
    photo_delivery_method character varying(20),
    photo_hard_disk_delivery_date date,
    photo_hard_disk_received boolean DEFAULT false,
    photo_approved boolean DEFAULT false,
    video_drive_link text,
    num_videos integer DEFAULT 0,
    video_camera_used text,
    video_upload_notes text,
    video_included_file_format character varying(50),
    video_first_clip text,
    video_last_clip text,
    video_delivery_method character varying(20),
    video_hard_disk_delivery_date date,
    video_hard_disk_received boolean DEFAULT false,
    video_approved boolean DEFAULT false,
    media_status character varying(20) DEFAULT 'Pending'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    photo_reupload_remarks text,
    video_reupload_remarks text,
    verification_draft jsonb
);
